In [1]:
from struct_dbn import dynamicBN
import scipy.stats as stats
import numpy as np
import math

In [2]:
config_aw = {"T": 20,
          "ncycles": 0.16*3600*24*365,
          "d0_mean": 0.11,
          "dcrit": 20,
          "q_mean": 10.21,
          "q_cov": 0.25,
          "time_variant_q": True, 
          "epsilonq_std": 0.05}
aw_comp = dynamicBN(config_aw)
print(aw_comp.time_variant_q)
print(aw_comp.epsilonq_std)

cg_params = {"lnC_mean": -26.445,
             "lnC_std": 0.122,
             "m": 3,
             "Ynormal_mean": 1,
             "Ynormal_cov": 0.1,
             "nsamples": 1e7}
aw_comp.crack_growth(cg_params)


n_dstates= 30
n_qstates = 20
aw_comp.transition_models(n_dstates, n_qstates)

True
0


(array([0.00000000e+00, 1.10000000e-01, 8.20357143e-01, 1.53071429e+00,
        2.24107143e+00, 2.95142857e+00, 3.66178571e+00, 4.37214286e+00,
        5.08250000e+00, 5.79285714e+00, 6.50321429e+00, 7.21357143e+00,
        7.92392857e+00, 8.63428571e+00, 9.34464286e+00, 1.00550000e+01,
        1.07653571e+01, 1.14757143e+01, 1.21860714e+01, 1.28964286e+01,
        1.36067857e+01, 1.43171429e+01, 1.50275000e+01, 1.57378571e+01,
        1.64482143e+01, 1.71585714e+01, 1.78689286e+01, 1.85792857e+01,
        1.92896429e+01, 2.00000000e+01, 1.00000000e+20]),
 array([1.00000000e-20, 1.29169526e+00, 2.58339052e+00, 3.87508578e+00,
        5.16678104e+00, 6.45847630e+00, 7.75017156e+00, 9.04186682e+00,
        1.03335621e+01, 1.16252573e+01, 1.29169526e+01, 1.42086479e+01,
        1.55003431e+01, 1.67920384e+01, 1.80837336e+01, 1.93754289e+01,
        2.06671242e+01, 2.19588194e+01, 2.32505147e+01, 2.45422099e+01,
        1.00000000e+20]))

In [3]:
np.max(aw_comp.qq)

True
0.05


(array([0.00000000e+00, 1.10000000e-01, 2.24892857e+00, 4.38785714e+00,
        6.52678571e+00, 8.66571429e+00, 1.08046429e+01, 1.29435714e+01,
        1.50825000e+01, 1.72214286e+01, 1.93603571e+01, 2.14992857e+01,
        2.36382143e+01, 2.57771429e+01, 2.79160714e+01, 3.00550000e+01,
        3.21939286e+01, 3.43328571e+01, 3.64717857e+01, 3.86107143e+01,
        4.07496429e+01, 4.28885714e+01, 4.50275000e+01, 4.71664286e+01,
        4.93053571e+01, 5.14442857e+01, 5.35832143e+01, 5.57221429e+01,
        5.78610714e+01, 6.00000000e+01, 1.00000000e+20]),
 array([1.00000000e-20, 1.97681020e+00, 3.95362041e+00, 5.93043061e+00,
        7.90724081e+00, 9.88405102e+00, 1.18608612e+01, 1.38376714e+01,
        1.58144816e+01, 1.77912918e+01, 1.97681020e+01, 2.17449122e+01,
        2.37217224e+01, 2.56985326e+01, 2.76753428e+01, 2.96521531e+01,
        3.16289633e+01, 3.36057735e+01, 3.55825837e+01, 3.75593939e+01,
        1.00000000e+20]))

In [4]:
config_bw = {"T": 20,
          "ncycles": 0.16*3600*24*365,
          "d0_mean": 0.11,
          "dcrit": 60,
          "q_mean": 7.4,
          "q_cov": 0.25,
          "time_variant_q": True, 
          "epsilonq_std": 0.05}
bw_comp = dynamicBN(config_bw)
print(bw_comp.time_variant_q)
print(bw_comp.epsilonq_std)

cg_params = {"lnC_mean": -26.043,
             "lnC_std": 0.403,
             "m": 3,
             "Ynormal_mean": 1,
             "Ynormal_cov": 0.1,
             "nsamples": 1e7}
bw_comp.crack_growth(cg_params)

n_dstates= 30
n_qstates = 20
bw_comp.transition_models(n_dstates, n_qstates)

True
0


(array([0.00000000e+00, 1.10000000e-01, 2.24892857e+00, 4.38785714e+00,
        6.52678571e+00, 8.66571429e+00, 1.08046429e+01, 1.29435714e+01,
        1.50825000e+01, 1.72214286e+01, 1.93603571e+01, 2.14992857e+01,
        2.36382143e+01, 2.57771429e+01, 2.79160714e+01, 3.00550000e+01,
        3.21939286e+01, 3.43328571e+01, 3.64717857e+01, 3.86107143e+01,
        4.07496429e+01, 4.28885714e+01, 4.50275000e+01, 4.71664286e+01,
        4.93053571e+01, 5.14442857e+01, 5.35832143e+01, 5.57221429e+01,
        5.78610714e+01, 6.00000000e+01, 1.00000000e+20]),
 array([1.00000000e-20, 8.54484742e-01, 1.70896948e+00, 2.56345423e+00,
        3.41793897e+00, 4.27242371e+00, 5.12690845e+00, 5.98139319e+00,
        6.83587793e+00, 7.69036268e+00, 8.54484742e+00, 9.39933216e+00,
        1.02538169e+01, 1.11083016e+01, 1.19627864e+01, 1.28172711e+01,
        1.36717559e+01, 1.45262406e+01, 1.53807254e+01, 1.62352101e+01,
        1.00000000e+20]))

In [6]:
config_md = {"T": 20,
          "ncycles": 0.16*3600*24*365,
          "d0_mean": 0.11,
          "dcrit": 60,
          "q_mean": 6.74,
          "q_cov": 0.25,
          "time_variant_q": True, 
          "epsilonq_std": 0.05}
md_comp = dynamicBN(config_md)
print(md_comp.time_variant_q)
print(md_comp.epsilonq_std)

cg_params = {"lnC_mean": -26.122,
             "lnC_std": 0.396,
             "m": 3,
             "Ynormal_mean": 1,
             "Ynormal_cov": 0.1,
             "nsamples": 1e7}
md_comp.crack_growth(cg_params)

n_dstates= 30
n_qstates = 20
md_comp.transition_models(n_dstates, n_qstates)

(array([[0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]]))

In [7]:
belief0 = np.zeros((3, n_dstates*n_qstates))
belief0[0] = aw_comp.b0
belief0[1] = bw_comp.b0
belief0[2] = md_comp.b0

T0 = np.zeros((3, 21, n_dstates*n_qstates, n_dstates*n_qstates))
T0[0] = aw_comp.T0
T0[1] = bw_comp.T0
T0[2] = md_comp.T0

Tr = np.zeros((3, 21, n_dstates*n_qstates, n_dstates*n_qstates))
Tr[0] = aw_comp.Tr
Tr[1] = bw_comp.Tr
Tr[2] = md_comp.Tr

d_interv = np.zeros((3, n_dstates+1))
d_interv[0] = aw_comp.d_interv
d_interv[1] = bw_comp.d_interv
d_interv[2] = md_comp.d_interv

q_interv = np.zeros((3, n_qstates+1))
q_interv[0] = aw_comp.q_interv
q_interv[1] = bw_comp.q_interv
q_interv[2] = md_comp.q_interv


{'ins_monitor': array([[1.54319127e-01, 4.44688352e-03, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [5.22866633e-03, 1.45051922e-01, 8.48542252e-03, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [3.20073502e-15, 1.00489793e-02, 1.36190529e-01, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        ...,
        [1.20796240e-41, 5.74105592e-37, 1.42621253e-32, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [6.61426140e-42, 1.83729243e-37, 2.85512285e-33, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [4.95009238e-44, 1.03397705e-39, 1.23457552e-35, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00]]),
 'monitor': array([[9.71990960e-01, 2.80090399e-02, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [3.29331594e-02, 9.13620750e-01, 5.34460902e-02, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],

In [9]:
belief0_eps = np.array([0.1, 0.25])
# epsilon_twin = np.random.beta(2,10,(1000000,1))
# eps_interv = np.arange(11)*0.1
# import matplotlib.pyplot as plt
# plt.hist(epsilon_twin,epsilon_interv)
# belief0_eps, _ = np.histogram(epsilon_twin, eps_interv)
# belief0_eps = belief0_eps/np.sum(belief0_eps)

n_twinstates = 3
belief0_twin = np.zeros(n_twinstates)
belief0_twin[-1] = 1
# No-nothing (0, 1)
T0_twin = np.zeros((n_twinstates, n_twinstates))
T0_twin[0,:] = np.array([0, 1, 0])
T0_twin[1,:] = np.array([0, 1, 0])
T0_twin[2,:] = np.array([0, 0, 1])

# Repair component without install sensor (4)
Tr_twin = np.zeros((n_twinstates, n_twinstates))
Tr_twin[0,:] = np.array([0, 0, 1])
Tr_twin[1,:] = np.array([0, 0, 1])
Tr_twin[2,:] = np.array([0, 0, 1])

# (Re)install sensor  (2, 3, 5)
Ts_twin = np.zeros((n_twinstates, n_twinstates))
Ts_twin[0,:] = np.array([1, 0, 0])
Ts_twin[1,:] = np.array([1, 0, 0])
Ts_twin[2,:] = np.array([1, 0, 0])
T0_twin, Tr_twin, Ts_twin

In [10]:
obs_params = {"inspect": True,
              "monitor": True,
              "error_cov": 0.07}
aw_comp.observation_models(obs_params)
bw_comp.observation_models(obs_params)

In [11]:
O_ins = np.zeros((2, n_dstates*n_qstates, 2*n_qstates))
O_ins[0] = aw_comp.O['ins']
O_ins[1] = bw_comp.O['ins']

O_monitor = np.zeros((2, n_dstates*n_qstates, 2*n_qstates))
O_monitor[0] = aw_comp.O['monitor']
O_monitor[1] = bw_comp.O['monitor']

O_ins_monitor = np.zeros((2, n_dstates*n_qstates, 2*n_qstates))
O_ins_monitor[0] = aw_comp.O['ins_monitor']
O_ins_monitor[1] = bw_comp.O['ins_monitor']

In [14]:
np.savez_compressed('Owf203020_Tw03', q_interv=q_interv, d_interv=d_interv,
         belief0=belief0, belief0_twin=belief0_twin, belief0_eps=belief0_eps,
         T0=T0, Tr=Tr, 
         T0_twin=T0_twin, Tr_twin=Tr_twin, Ts_twin=Ts_twin, 
         O_ins=O_ins, O_monitor=O_monitor, O_ins_monitor=O_ins_monitor)

(array([1.321000e-04, 7.228000e-04, 3.241300e-03, 1.108780e-02,
        2.946760e-02, 6.109870e-02, 9.848310e-02, 1.238095e-01,
        1.210004e-01, 9.159110e-02, 5.419120e-02, 2.495820e-02,
        9.020100e-03, 2.478900e-03, 5.349000e-04, 9.200000e-05,
        1.460000e-05, 1.300000e-06, 0.000000e+00, 0.000000e+00,
        7.680000e-05, 4.250000e-04, 1.872200e-03, 6.472700e-03,
        1.713670e-02, 3.562950e-02, 5.729550e-02, 7.197590e-02,
        7.023870e-02, 5.335650e-02, 3.145580e-02, 1.452520e-02,
        5.214600e-03, 1.436900e-03, 3.196000e-04, 5.050000e-05,
        5.200000e-06, 8.000000e-07, 2.000000e-07, 0.000000e+00,
        0.000000e+00, 2.000000e-07, 3.400000e-06, 1.060000e-05,
        2.730000e-05, 5.910000e-05, 8.910000e-05, 1.144000e-04,
        1.130000e-04, 8.450000e-05, 4.820000e-05, 2.330000e-05,
        9.200000e-06, 2.300000e-06, 8.000000e-07, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.00

In [13]:
md_comp.Tr

array([[[0.0001332, 0.0007279, 0.0032729, ..., 0.       , 0.       ,
         0.       ],
        [0.0001332, 0.0007279, 0.0032729, ..., 0.       , 0.       ,
         0.       ],
        [0.0001332, 0.0007279, 0.0032729, ..., 0.       , 0.       ,
         0.       ],
        ...,
        [0.0001332, 0.0007279, 0.0032729, ..., 0.       , 0.       ,
         0.       ],
        [0.0001332, 0.0007279, 0.0032729, ..., 0.       , 0.       ,
         0.       ],
        [0.0001332, 0.0007279, 0.0032729, ..., 0.       , 0.       ,
         0.       ]],

       [[0.0001332, 0.0007279, 0.0032729, ..., 0.       , 0.       ,
         0.       ],
        [0.0001332, 0.0007279, 0.0032729, ..., 0.       , 0.       ,
         0.       ],
        [0.0001332, 0.0007279, 0.0032729, ..., 0.       , 0.       ,
         0.       ],
        ...,
        [0.0001332, 0.0007279, 0.0032729, ..., 0.       , 0.       ,
         0.       ],
        [0.0001332, 0.0007279, 0.0032729, ..., 0.       , 0.       ,
   